/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TierlistRouteImport } from './routes/tierlist'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatchMatchIdRouteImport } from './routes/match.$matchId'
import { Route as ChampionNameRouteImport } from './routes/champion.$name'
import { Route as AccountGameNameTagLineRouteImport } from './routes/account.$gameName.$tagLine'

const TierlistRoute = TierlistRouteImport.update({
  id: '/tierlist',
  path: '/tierlist',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchMatchIdRoute = MatchMatchIdRouteImport.update({
  id: '/match/$matchId',
  path: '/match/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChampionNameRoute = ChampionNameRouteImport.update({
  id: '/champion/$name',
  path: '/champion/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountGameNameTagLineRoute = AccountGameNameTagLineRouteImport.update({
  id: '/account/$gameName/$tagLine',
  path: '/account/$gameName/$tagLine',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/players': typeof PlayersRoute
  '/tierlist': typeof TierlistRoute
  '/champion/$name': typeof ChampionNameRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/account/$gameName/$tagLine': typeof AccountGameNameTagLineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/players': typeof PlayersRoute
  '/tierlist': typeof TierlistRoute
  '/champion/$name': typeof ChampionNameRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/account/$gameName/$tagLine': typeof AccountGameNameTagLineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/players': typeof PlayersRoute
  '/tierlist': typeof TierlistRoute
  '/champion/$name': typeof ChampionNameRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/account/$gameName/$tagLine': typeof AccountGameNameTagLineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/players'
    | '/tierlist'
    | '/champion/$name'
    | '/match/$matchId'
    | '/account/$gameName/$tagLine'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/players'
    | '/tierlist'
    | '/champion/$name'
    | '/match/$matchId'
    | '/account/$gameName/$tagLine'
  id:
    | '__root__'
    | '/'
    | '/players'
    | '/tierlist'
    | '/champion/$name'
    | '/match/$matchId'
    | '/account/$gameName/$tagLine'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlayersRoute: typeof PlayersRoute
  TierlistRoute: typeof TierlistRoute
  ChampionNameRoute: typeof ChampionNameRoute
  MatchMatchIdRoute: typeof MatchMatchIdRoute
  AccountGameNameTagLineRoute: typeof AccountGameNameTagLineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tierlist': {
      id: '/tierlist'
      path: '/tierlist'
      fullPath: '/tierlist'
      preLoaderRoute: typeof TierlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$matchId': {
      id: '/match/$matchId'
      path: '/match/$matchId'
      fullPath: '/match/$matchId'
      preLoaderRoute: typeof MatchMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/champion/$name': {
      id: '/champion/$name'
      path: '/champion/$name'
      fullPath: '/champion/$name'
      preLoaderRoute: typeof ChampionNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/$gameName/$tagLine': {
      id: '/account/$gameName/$tagLine'
      path: '/account/$gameName/$tagLine'
      fullPath: '/account/$gameName/$tagLine'
      preLoaderRoute: typeof AccountGameNameTagLineRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlayersRoute: PlayersRoute,
  TierlistRoute: TierlistRoute,
  ChampionNameRoute: ChampionNameRoute,
  MatchMatchIdRoute: MatchMatchIdRoute,
  AccountGameNameTagLineRoute: AccountGameNameTagLineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
